### ISSUE TITLE
can't work with vue@2.0 ssr

### ISSUE THREAD

**Issue by doabit** [vuejs/vue-resource#350]
When add `import VueResource from 'vue-resource'` to https://github.com/yyx990803/vue-ssr-demo/blob/master/src/store.js, then run `npm run build` and `npm start`, visit `http://localhost:3000`, it'll throw error

```bash
ReferenceError: window is not defined
    at Object.<anonymous> (__vue_ssr_bundle__:5715:18)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:79:71)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.module.exports.res (__vue_ssr_bundle__:5006:65)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:7494:63)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at __vue_ssr_bundle__:65:18
    at Object.<anonymous> (__vue_ssr_bundle__:68:10)
```

**Comment by jiakeqi** [comment]
I get same error 😭
````
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/jk/Desktop/fe-douban/node_modules/vue-resource/dist/vue-resource.common.js:13:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (__vue_ssr_bundle__:3216:18)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:1350:71)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.module.exports.exports.default.name (__vue_ssr_bundle__:138:66)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:3241:63)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
````

**Comment by jiakeqi** [comment]
@doabit hey, I already fix 💯  it's not bug
````js
import Vue from 'vue'
const inBrowser = typeof window !== 'undefined'
if (inBrowser) {
  Vue.use(require('vue-resource'))
} 
````

**Comment by doabit** [comment]
@jiakeqi Thanks.

**Comment by pi0** [comment]
Former solutions just hides the problem, #452 fixes this issue :)
